apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: gcr.io/qwiklabs-gcp-04-886229844db0/demo-product-service:v1.0.0
        ports:
        - containerPort: 8080
